language: perl
sudo: false
perl:
  - "5.20"
  - "5.18"
  - "5.14"
before_install:
    - "cpanm -n Devel::Cover::Report::Coveralls"
    - "cpanm Module::Build@0.4222"
    - "cpanm Module::Build::Pluggable Module::Build::Pluggable::CPANfile"
    - "git clone --branch master --depth 1 https://github.com/EMBL-EBI-GCA/BioSD.git ~/BioSD"
    - "cpanm --installdeps ~/BioSD"
    - "cpanm Carton"

install:
  - "carton install --deployment"

env:
  global:
    -PERL5LIB=$PERL5LIB:~/BioSD/lib
    -PERL5LIB=$PERL5LIB:/home/travis/build/FAANG/validate-metadata/local/lib/perl5

script:
  perl Build.PL && ./Build build && cover -test -report coveralls
