language: perl
sudo: false
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
    - "cpanm -n Devel::Cover::Report::Coveralls"
    - "cpanm Module::Build::Pluggable Module::Build::Pluggable::CPANfile"
before_script:
      
script:
  perl Build.PL && ./Build build && cover -test -report coveralls